# Generated by Django 2.2.7 on 2019-11-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='word',
            new_name='Word',
        ),
    ]
