# Generated by Django 2.2.7 on 2019-11-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191125_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='doc_id',
        ),
        migrations.CreateModel(
            name='WordFrequencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Document')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Words')),
            ],
        ),
    ]
